import random
import heapq
import math
import numpy as np
from gdpc import Block
from biome_palette import get_palette
import build_houses

# ─────────────────────────────────────────────
#  Helpers & Terrain Evaluation
# ─────────────────────────────────────────────

def get_height(heightmap, x, z, origin):
    ox, oz = origin
    lx, lz = x - ox, z - oz
    if 0 <= lx < heightmap.shape[0] and 0 <= lz < heightmap.shape[1]:
        return int(heightmap[lx, lz])
    return None

def in_bounds(x, z, heightmap, origin):
    ox, oz = origin
    lx, lz = x - ox, z - oz
    return 0 <= lx < heightmap.shape[0] and 0 <= lz < heightmap.shape[1]

def is_water_ws(worldslice, x, z, origin):
    ox, oz = origin
    lx, lz = x - ox, z - oz
    sx, sz = worldslice.heightmaps["MOTION_BLOCKING_NO_LEAVES"].shape
    if not (0 <= lx < sx and 0 <= lz < sz): return False
    
    y = int(worldslice.heightmaps["MOTION_BLOCKING_NO_LEAVES"][lx, lz])
    for dy in range(0, 3):
        try:
            block = worldslice.getBlock((lx, y - dy, lz))
            if "water" in block.id or "kelp" in block.id or "seagrass" in block.id:
                return True
        except Exception:
            pass
    return False

def slope_in_area(heightmap, origin, x, z, width=5, depth=5):
    heights = []
    for dx in range(width):
        for dz in range(depth):
            h = get_height(heightmap, x + dx, z + dz, origin)
            if h is not None: heights.append(h)
    if not heights: return 999
    return max(heights) - min(heights)

def is_valid_site(worldslice, heightmap, origin, x, z, width=5, depth=5, max_slope=2):
    if not in_bounds(x, z, heightmap, origin) or not in_bounds(x + width, z + depth, heightmap, origin):
        return False
    if slope_in_area(heightmap, origin, x, z, width, depth) > max_slope: 
        return False
    for dx in range(0, width, 2):
        for dz in range(0, depth, 2):
            if is_water_ws(worldslice, x + dx, z + dz, origin): return False
    return True

# ─────────────────────────────────────────────
#  Footprint Management
# ─────────────────────────────────────────────

def footprint(hx, hz, width=5, depth=5, padding=2):
    cells = set()
    for dx in range(-padding, width + padding):
        for dz in range(-padding, depth + padding):
            cells.add((hx + dx, hz + dz))
    return cells

def overlaps_any(hx, hz, placed_footprints, width=5, depth=5, padding=2):
    fp = footprint(hx, hz, width, depth, padding)
    for existing in placed_footprints:
        if fp & existing: return True
    return False

# ─────────────────────────────────────────────
#  Algorithm 1: A* Path-finder 
# ─────────────────────────────────────────────

class Node:
    def __init__(self, pos, g=0, h=0, parent=None):
        self.pos = pos
        self.g = g
        self.h = h
        self.f = g + h
        self.parent = parent
    def __lt__(self, other):
        return self.f < other.f

def heuristic(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])

def astar_to_network(start, existing_network, heightmap, origin, worldslice=None, water_penalty=50):
    """Finds a short path from a door to the main road network generated by the layout algorithm."""
    if not existing_network: return []
    if start in existing_network: return [start]

    ox, oz = origin
    sx, sz = heightmap.shape
    closest_goal = min(existing_network, key=lambda p: heuristic(start, p))

    open_list = []
    closed = set()
    heapq.heappush(open_list, Node(start, 0, heuristic(start, closest_goal)))
    directions = [(1, 0), (-1, 0), (0, 1), (0, -1)]

    def valid(pos):
        lx, lz = pos[0] - ox, pos[1] - oz
        return 0 <= lx < sx and 0 <= lz < sz

    while open_list:
        current = heapq.heappop(open_list)
        if current.pos in existing_network:
            path = []
            while current:
                path.append(current.pos)
                current = current.parent
            return path[::-1]

        closed.add(current.pos)
        for dx, dz in directions:
            nxt = (current.pos[0] + dx, current.pos[1] + dz)
            if not valid(nxt) or nxt in closed: continue

            h1 = get_height(heightmap, current.pos[0], current.pos[1], origin)
            h2 = get_height(heightmap, nxt[0], nxt[1], origin)
            slope_cost = abs(h1 - h2) * 5
            water_cost = water_penalty if (worldslice and is_water_ws(worldslice, nxt[0], nxt[1], origin)) else 0

            cost = 1 + slope_cost + water_cost
            heapq.heappush(open_list, Node(nxt, current.g + cost, heuristic(nxt, closest_goal), current))
    return []

# ─────────────────────────────────────────────
#  Algorithm 2: Minecraft Jigsaw Layout Generator
# ─────────────────────────────────────────────

def generate_layout(worldslice, heightmap, origin, num_houses, num_farms):
    ox, oz = origin
    sx, sz = heightmap.shape
    
    # Find a flat center for the main plaza
    center = None
    for _ in range(100):
        cx = ox + random.randint(sx // 4, 3 * sx // 4)
        cz = oz + random.randint(sz // 4, 3 * sz // 4)
        if is_valid_site(worldslice, heightmap, origin, cx-3, cz-3, 7, 7, max_slope=2):
            center = (cx, cz)
            break
    if center is None: center = (ox + sx // 2, oz + sz // 2)
    cx, cz = center

    road_tiles = set()
    houses = []
    farms = []
    placed_footprints = []
    
    # Create the central plaza
    for dx in range(-3, 4):
        for dz in range(-3, 4):
            if math.hypot(dx, dz) <= 3:
                road_tiles.add((cx + dx, cz + dz))
    # Reserve the center for the well
    placed_footprints.append(footprint(cx-2, cz-2, 5, 5, padding=1))
    
    # Queue up the 4 main roads branching from the center
    # Format: (x, z, dx, dz, max_length)
    queue = [
        (cx, cz - 3, 0, -1, random.randint(15, 30)), # North
        (cx, cz + 3, 0, 1, random.randint(15, 30)),  # South
        (cx + 3, cz, 1, 0, random.randint(15, 30)),  # East
        (cx - 3, cz, -1, 0, random.randint(15, 30))  # West
    ]
    
    target_buildings = num_houses + num_farms
    buildings_placed = 0
    branches = 0
    max_branches = 20 # Prevent infinite sprawl
    
    while queue and buildings_placed < target_buildings:
        rx, rz, dx, dz, length = queue.pop(0)
        
        for step in range(length):
            rx += dx
            rz += dz
            
            if not in_bounds(rx, rz, heightmap, origin): break
            
            road_tiles.add((rx, rz))

            if step % 2 == 0:
                for ndx, ndz in [(1,0), (-1,0), (0,1), (0,-1)]:
                     if random.random() < 0.25:
                         road_tiles.add((rx + ndx, rz + ndz))
                         

            if step % 6 == 0 and step > 3:
                is_farm = (len(farms) < num_farms) and (random.random() < 0.3 or len(houses) >= num_houses)
                width = 9 if is_farm else 5
                depth = 9 if is_farm else random.choice([4, 6])
                

                sides = []
                if dx == 0: # Road runs North/South
                    sides = [
                        (rx + 2, rz - depth//2, "west"),          # Right side
                        (rx - width - 1, rz - depth//2, "east")   # Left side
                    ]
                else:       # Road runs East/West
                    sides = [
                        (rx - width//2, rz + 2, "north"),         # Bottom side
                        (rx - width//2, rz - depth - 1, "south")  # Top side
                    ]
                    
                random.shuffle(sides)
                for hx, hz, facing in sides:
                    if not in_bounds(hx, hz, heightmap, origin) or not in_bounds(hx+width, hz+depth, heightmap, origin):
                        continue
                        
                    if is_valid_site(worldslice, heightmap, origin, hx, hz, width, depth, max_slope=3):
                        if not overlaps_any(hx, hz, placed_footprints, width, depth, padding=2):
                            
   
                            hy = get_height(heightmap, hx, hz, origin)
                            if is_farm:
                                farms.append((hx, hy, hz))
                            else:
                                houses.append((hx, hy, hz, depth, facing))
                                
                            placed_footprints.append(footprint(hx, hz, width, depth, padding=2))
                            buildings_placed += 1
                            
                            # Draw a small path connecting the door strictly to the road network
                            if not is_farm:
                                door_x, door_z = build_houses.get_door_outside_pos(hx, hz, depth, facing)
                                path = astar_to_network((door_x, door_z), road_tiles, heightmap, origin, worldslice)
                                road_tiles.update(path)
                            else:
                                path = astar_to_network((hx + 4, hz - 1), road_tiles, heightmap, origin, worldslice)
                                road_tiles.update(path)
                            break
                            
        # Reached the end of the road. If we still need buildings, fork the road
        if buildings_placed < target_buildings and branches < max_branches:
            branches += 2
            if dx == 0: # Was N/S, branch E/W
                queue.append((rx, rz, 1, 0, random.randint(10, 20)))
                queue.append((rx, rz, -1, 0, random.randint(10, 20)))
            else:       # Was E/W, branch N/S
                queue.append((rx, rz, 0, 1, random.randint(10, 20)))
                queue.append((rx, rz, 0, -1, random.randint(10, 20)))
                
    return houses, farms, road_tiles, center

# ─────────────────────────────────────────────
#  Decor & Construction
# ─────────────────────────────────────────────

def build_well(editor, x, y, z):

    # Foundation and Walls
    for dx in range(-1, 2):
        for dz in range(-1, 2):
            editor.placeBlock((x+dx, y-2, z+dz), Block("cobblestone"))
            editor.placeBlock((x+dx, y-1, z+dz), Block("cobblestone"))
            
            if dx == 0 and dz == 0:
                editor.placeBlock((x, y-1, z), Block("water"))
                editor.placeBlock((x, y, z), Block("air"))
            else:
                editor.placeBlock((x+dx, y, z+dz), Block("cobblestone"))
    
    # Pillars
    editor.placeBlock((x-1, y+1, z-1), Block("cobblestone_wall"))
    editor.placeBlock((x-1, y+1, z+1), Block("cobblestone_wall"))
    editor.placeBlock((x+1, y+1, z-1), Block("cobblestone_wall"))
    editor.placeBlock((x+1, y+1, z+1), Block("cobblestone_wall"))
    
    # Roof
    for dx in range(-1, 2):
        for dz in range(-1, 2):
            editor.placeBlock((x+dx, y+2, z+dz), Block("cobblestone_slab"))

def place_road(editor, heightmap, origin, road_tiles, worldslice):
    for (x, z) in road_tiles:
        y = get_height(heightmap, x, z, origin)
        if y is None: continue

        # Water bridges vs Dirt paths
        if is_water_ws(worldslice, x, z, origin):
            editor.placeBlock((x, y, z), Block("oak_planks"))
            editor.placeBlock((x, y+1, z), Block("air"))
            editor.placeBlock((x, y+2, z), Block("air"))
        else:
            road_block = random.choice(["dirt_path", "dirt_path", "dirt_path", "coarse_dirt"])
            editor.placeBlock((x, y-1, z), Block(road_block))
            editor.placeBlock((x, y, z), Block("air"))
            editor.placeBlock((x, y+1, z), Block("air"))

# ─────────────────────────────────────────────
#  Master generate function
# ─────────────────────────────────────────────

def generate_village(editor, buildArea, heightmap, worldslice, num_houses=10, num_farms=1):
    origin = (buildArea.offset.x, buildArea.offset.z)
    
    # 1. & 2. Spatial Layout utilizing the Jigsaw algorithm
    print("Tracing jigsaw street layouts...")
    houses, farms, road_tiles, center = generate_layout(worldslice, heightmap, origin, num_houses, num_farms)

    # 3. Terrain Modding (Roads and Bridges)
    print("Weaving road network and bridges...")
    place_road(editor, heightmap, origin, road_tiles, worldslice)

    # 4. Central Monument
    print("Building central well...")
    cx, cz = center
    cy = get_height(heightmap, cx, cz, origin)
    if cy is not None: build_well(editor, cx, cy, cz)

    # 5. Build Structures
    palette = get_palette(worldslice, heightmap, origin)
    print("Constructing buildings...")
    
    for hx, hy, hz, depth, facing in houses:
        if random.random() < 0.4:
            build_houses.build_2fhouse(editor, hx, hy, hz, depth, palette, facing)
        else:
            build_houses.build_1fhouse(editor, hx, hy, hz, depth, 4, palette, facing)
            
    for fx, fy, fz in farms:
        build_houses.build_farm(editor, fx, fy, fz, width=9, depth=9, palette=palette)
        
    print(f"Village generation complete. Placed {len(houses)} houses and {len(farms)} farms.")
